version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-2.c9eu0ciek6g6.us-east-1.rds.amazonaws.com:3310/bank
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: VladKuli
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: VladKuli
      MYSQL_DATABASE: bank
      MYSQL_USER: admin
      MYSQL_PASSWORD: VladKuli